matrix:
  include:
    - sudo: required
      language: cpp
      os: android
      compiler: g++
      services: docker
      env: TARGET=android
    - sudo: required
      language: cpp
      os: linux
      compiler: g++
      services: docker
      env: TARGET=linux

before_install: docker build -t qmlalljoyn .travis/$TARGET/

script: docker run -ti --name qmlalljoynintrospector -v $PWD:/source:ro qmlalljoyn /build.sh
